files:
  - source: /src/main/resources/assets/tacz/lang/en_us.json
    translation: /src/main/resources/assets/tacz/lang/%locale%.json
  - source: /src/main/resources/assets/tacz/custom/tacz_default_gun/assets/tacz/lang/en_us.json
    translation: /src/main/resources/assets/tacz/custom/tacz_default_gun/assets/tacz/lang/%locale%.json
